"""add criteria_fingerprint to searchjob

Revision ID: 74d983f20c05
Revises: 23746613c8c7
Create Date: 2026-06-28 16:53:54.620480

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74d983f20c05"
down_revision: str | Sequence[str] | None = "23746613c8c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default='' lets Postgres add the NOT NULL column to existing rows
    # without a full-table rewrite.  The Python-level model default ("") means
    # new inserts never rely on the server default, so it's harmless to keep.
    op.add_column(
        "searchjob",
        sa.Column(
            "criteria_fingerprint",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="",
        ),
    )
    op.create_index(
        op.f("ix_searchjob_criteria_fingerprint"),
        "searchjob",
        ["criteria_fingerprint"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_searchjob_criteria_fingerprint"), table_name="searchjob")
    op.drop_column("searchjob", "criteria_fingerprint")
    # ### end Alembic commands ###
