"""baseline schema with multi-user

Revision ID: d3a47bb1e460
Revises: 
Create Date: 2026-06-16 16:01:44.037306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd3a47bb1e460'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insightscache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('section', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section', 'region', name='uq_insightscache_section_region')
    )
    op.create_index(op.f('ix_insightscache_region'), 'insightscache', ['region'], unique=False)
    op.create_index(op.f('ix_insightscache_section'), 'insightscache', ['section'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('resume',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_user_id'), 'resume', ['user_id'], unique=False)
    op.create_table('savedsearch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('criteria_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_search_job_id', sa.Uuid(), nullable=True),
    sa.Column('seen_keys_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_diffed_job_id', sa.Uuid(), nullable=True),
    sa.Column('last_new_ids_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savedsearch_user_id'), 'savedsearch', ['user_id'], unique=False)
    op.create_table('searchjob',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('criteria_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'complete', 'failed', name='searchjobstatus'), nullable=False),
    sa.Column('total_results', sa.Integer(), nullable=False),
    sa.Column('completed_adapters', sa.Integer(), nullable=False),
    sa.Column('total_adapters', sa.Integer(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_searchjob_user_id'), 'searchjob', ['user_id'], unique=False)
    op.create_table('jobposting',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('search_job_id', sa.Uuid(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('remote_status', sa.Enum('remote', 'hybrid', 'onsite', 'unspecified', name='remotestatus'), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('compensation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('posted_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['search_job_id'], ['searchjob.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobposting_search_job_id'), 'jobposting', ['search_job_id'], unique=False)
    op.create_index(op.f('ix_jobposting_user_id'), 'jobposting', ['user_id'], unique=False)
    op.create_table('application',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_posting_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('preparing', 'prep_failed', 'pending', 'rejected', 'submitted', 'failed', 'saved', name='applicationstatus'), nullable=False),
    sa.Column('prep_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prep_error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tailored_resume_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resume_diff_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cover_letter_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resume_data_yaml', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cover_letter_data_yaml', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('match_rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_gaps', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tailoring_failed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_posting_id'], ['jobposting.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_job_posting_id'), 'application', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_application_user_id'), 'application', ['user_id'], unique=False)
    op.create_table('auditlog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('board_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditlog_application_id'), 'auditlog', ['application_id'], unique=False)
    op.create_index(op.f('ix_auditlog_user_id'), 'auditlog', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditlog_user_id'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_application_id'), table_name='auditlog')
    op.drop_table('auditlog')
    op.drop_index(op.f('ix_application_user_id'), table_name='application')
    op.drop_index(op.f('ix_application_job_posting_id'), table_name='application')
    op.drop_table('application')
    op.drop_index(op.f('ix_jobposting_user_id'), table_name='jobposting')
    op.drop_index(op.f('ix_jobposting_search_job_id'), table_name='jobposting')
    op.drop_table('jobposting')
    op.drop_index(op.f('ix_searchjob_user_id'), table_name='searchjob')
    op.drop_table('searchjob')
    op.drop_index(op.f('ix_savedsearch_user_id'), table_name='savedsearch')
    op.drop_table('savedsearch')
    op.drop_index(op.f('ix_resume_user_id'), table_name='resume')
    op.drop_table('resume')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_insightscache_section'), table_name='insightscache')
    op.drop_index(op.f('ix_insightscache_region'), table_name='insightscache')
    op.drop_table('insightscache')
    # ### end Alembic commands ###
